server:
  port: 8084
  
spring:
  codec:
    max-in-memory-size: 10MB
    
  main:
    allow-bean-definition-overriding: true
    banner-mode: "off"
    
  application:
    name: UserService
    
  data:
    mongodb:
      uri: ${mongodb_url}
      database: ${mongodb_database} 
  
  rabbitmq:
    host: ${rabbitmq_host}
    port: ${rabbitmq_port}
    username: ${rabbitmq_username}
    password: ${rabbitmq_password}
    queue-listener: ${rabbitmq_queue_listener}


eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone:  ${eureka_url:http://localhost:8761/eureka/}

  instance:
    hostname: ${HOSTNAME:${spring.application.name}}
    preferIpAddress: false
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}:${server.port}
