server:
  port: 8086
  
spring:
  codec:
    max-in-memory-size: 10MB
    
  main:
    allow-bean-definition-overriding: true
    banner-mode: "off"
    
  application:
    name: UserService
    
  data:
    mongodb:
      uri: ${mongodb_url}
      database: ${mongodb_database} 
  
  rabbitmq:
    host: ${rabbitmq_host}
    port: ${rabbitmq_port}
    username: ${rabbitmq_username}
    password: ${rabbitmq_password}
    queue-listener: ${rabbitmq_queue_listener}